# Generated by Django 5.2.15 on 2026-06-29 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health.status')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('transmission_mode', models.CharField(max_length=100)),
                ('incubation_period', models.IntegerField()),
                ('prevention', models.TextField()),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health.status')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity_level', models.CharField(max_length=20)),
                ('symptom_code', models.CharField(max_length=20)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health.status')),
            ],
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('risk_level', models.CharField(max_length=20)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.disease')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.patient')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health.status')),
                ('symptoms', models.ManyToManyField(to='health.symptom')),
            ],
        ),
    ]
