# Generated by Django 5.2.15 on 2026-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='incubation_period',
            field=models.CharField(max_length=100),
        ),
    ]
